# -*- coding: utf-8 -*-
"""ENPH353_actual_finalCNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UOo-jz8dKZzd2AG7B3AO8kdHNAALufRe
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import json
import random
import cv2
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.utils.class_weight import compute_class_weight

IMAGE_DIR = "/content/drive/MyDrive/353_data/images/train"
REAL_LINE_DIR = "/content/drive/MyDrive/353_photos"

BASE_MODEL_KERAS_PATH = "/content/drive/MyDrive/sign_char_model.keras"
BASE_MODEL_TFLITE_PATH = "/content/drive/MyDrive/sign_char_model.tflite"

FINETUNED_MODEL_KERAS_PATH = "/content/drive/MyDrive/sign_char_model_finetuned.keras"
FINETUNED_MODEL_TFLITE_PATH = "/content/drive/MyDrive/sign_char_model_finetuned.tflite"

CLASSES_PATH = "/content/drive/MyDrive/sign_char_classes.json"

SPACE_TOKEN = " "
CLASSES = list("0123456789") + list("ABCDEFGHIJKLMNOPQRSTUVWXYZ") + [SPACE_TOKEN]
DISPLAY_CLASSES = [c if c != " " else "␠" for c in CLASSES]

CLASS_TO_IDX = {c: i for i, c in enumerate(CLASSES)}
IDX_TO_CLASS = {i: c for i, c in enumerate(CLASSES)}

print("num classes:", len(CLASSES))
print("classes:", DISPLAY_CLASSES)

files = sorted([
    f for f in os.listdir(IMAGE_DIR)
    if f.lower().endswith((".png", ".jpg", ".jpeg"))
])

real_files = sorted([
    f for f in os.listdir(REAL_LINE_DIR)
    if f.lower().endswith((".png", ".jpg", ".jpeg"))
])

print("num generated files:", len(files))
print("num real line files:", len(real_files))
print(files[:10])
print(real_files[:10])


def normalize_space_text(text: str) -> str:
    return text.replace("~", " ").upper()


def parse_filename(fname):
    """
    Expected generated filename style:
    <index>_<clue_type>_<clue_value>_<variant>.png
    """
    stem = os.path.splitext(fname)[0]
    parts = stem.split("_")

    index = parts[0]
    clue_type = normalize_space_text(parts[1])
    variant = parts[-1]
    clue_value = normalize_space_text("_".join(parts[2:-1]))

    return index, clue_type, clue_value, variant


def parse_line_filename(fname):
    """
    Real line filenames:
    - ABC~12_001.png  -> "ABC 12"
    - AB 12_001.png   -> "AB 12"
    """
    stem = os.path.splitext(fname)[0]
    text = stem.split("_")[0]
    return normalize_space_text(text)


for f in files[:10]:
    print(f, "->", parse_filename(f))

def order_points(pts):
    pts = np.array(pts, dtype=np.float32)
    s = pts.sum(axis=1)
    diff = np.diff(pts, axis=1)

    top_left = pts[np.argmin(s)]
    bottom_right = pts[np.argmax(s)]
    top_right = pts[np.argmin(diff)]
    bottom_left = pts[np.argmax(diff)]

    return np.array([top_left, top_right, bottom_right, bottom_left], dtype=np.float32)


def four_point_transform(image, pts, out_w=400, out_h=300):
    rect = order_points(pts)
    dst = np.array([
        [0, 0],
        [out_w - 1, 0],
        [out_w - 1, out_h - 1],
        [0, out_h - 1]
    ], dtype=np.float32)

    M = cv2.getPerspectiveTransform(rect, dst)
    warped = cv2.warpPerspective(image, M, (out_w, out_h))
    return warped


def detect_and_warp_sign(img_bgr, debug=False):
    """
    Match sign_detector logic more closely:
    - darker blue mask to avoid sky
    - candidate contour scoring
    - 400x300 warp
    """
    hsv = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2HSV)

    lower_blue = np.array([100, 120, 25])
    upper_blue = np.array([140, 255, 200])
    mask = cv2.inRange(hsv, lower_blue, upper_blue)

    mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, np.ones((7, 7), np.uint8), iterations=1)
    mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, np.ones((3, 3), np.uint8), iterations=1)
    mask = cv2.dilate(mask, np.ones((7, 7), np.uint8), iterations=1)

    H, W = mask.shape[:2]
    frame_area = float(H * W)

    cnts, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    if not cnts:
        return None, mask, None

    candidates = []
    for c in cnts:
        area = cv2.contourArea(c)
        if area < 0.004 * frame_area:
            continue

        x, y, w, h = cv2.boundingRect(c)
        if x <= 6 or y <= 6 or (x + w) >= (W - 6) or (y + h) >= (H - 6):
            continue

        rect = cv2.minAreaRect(c)
        rw, rh = rect[1]
        rw = max(float(rw), 1e-6)
        rh = max(float(rh), 1e-6)
        aspect = max(rw, rh) / min(rw, rh)

        if not (0.75 <= aspect <= 3.4):
            continue

        box_area = float(w * h) + 1e-6
        extent = float(area) / box_area

        hull = cv2.convexHull(c)
        hull_area = float(cv2.contourArea(hull)) + 1e-6
        solidity = float(area) / hull_area

        roi = mask[y:y+h, x:x+w]
        fill = float(np.count_nonzero(roi)) / float(roi.size + 1e-6)

        expected_aspect = 1.6
        aspect_score = 1.0 - min(1.0, abs(aspect - expected_aspect) / expected_aspect)

        score = (
            3.0 * (area / frame_area) +
            0.8 * extent +
            1.0 * aspect_score +
            0.4 * solidity +
            0.6 * fill
        )

        candidates.append((score, c))

    if not candidates:
        c = max(cnts, key=cv2.contourArea)
        candidates = [(0.0, c)]

    candidates = sorted(candidates, key=lambda x: x[0], reverse=True)[:10]

    best_warp = None
    best_quad = None
    best_score = -1e9

    for score, c in candidates:
        peri = cv2.arcLength(c, True)
        approx = cv2.approxPolyDP(c, 0.03 * peri, True)

        if len(approx) == 4:
            quad = approx.reshape(4, 2)
        else:
            rect = cv2.minAreaRect(c)
            quad = cv2.boxPoints(rect).astype(int)

        warped = four_point_transform(img_bgr, quad, out_w=400, out_h=300)

        if score > best_score:
            best_score = score
            best_warp = warped
            best_quad = quad

    if debug:
        dbg = img_bgr.copy()
        cv2.drawContours(dbg, [best_quad.astype(int)], -1, (0, 255, 0), 3)
        return best_warp, mask, dbg

    return best_warp, mask, None

def split_sign_lines(warped_bgr):
    """
    Match the sign_detector proportions.
    """
    h, w = warped_bgr.shape[:2]

    top_line = warped_bgr[int(0.05 * h):int(0.40 * h), int(0.30 * w):int(0.92 * w)]
    bottom_line = warped_bgr[int(0.55 * h):int(0.90 * h), int(0.05 * w):int(0.92 * w)]

    return top_line, bottom_line


def preprocess_training_crop(crop_bgr):
    """
    Must match runtime preprocessing exactly.
    """
    gray = cv2.cvtColor(crop_bgr, cv2.COLOR_BGR2GRAY)
    gray = cv2.equalizeHist(gray)
    gray = cv2.GaussianBlur(gray, (3, 3), 0)

    _, bw = cv2.threshold(
        gray, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU
    )

    h, w = bw.shape[:2]
    side = max(h, w) + 10

    canvas = np.zeros((side, side), dtype=np.uint8)
    y_off = (side - h) // 2
    x_off = (side - w) // 2
    canvas[y_off:y_off + h, x_off:x_off + w] = bw

    canvas = cv2.resize(canvas, (40, 40), interpolation=cv2.INTER_AREA)
    canvas = cv2.resize(canvas, (32, 32), interpolation=cv2.INTER_AREA)

    return canvas


def make_space_crop():
    """
    Explicit SPACE sample.
    """
    return np.zeros((32, 32), dtype=np.uint8)

def clean_blue_mask(mask):
    """
    Gentler than old notebook code.
    Preserves letters like P, R, B, 0.
    """
    m = mask.copy()
    m = cv2.medianBlur(m, 3)
    m = cv2.morphologyEx(m, cv2.MORPH_CLOSE, np.ones((2, 2), np.uint8), iterations=1)
    m = cv2.morphologyEx(m, cv2.MORPH_OPEN, np.ones((2, 2), np.uint8), iterations=1)
    return m


def strip_edges_if_needed(mask):
    """
    Remove border strips only if they look like vertical frame bars.
    """
    H, W = mask.shape[:2]
    col_ratio = np.sum(mask > 0, axis=0).astype(np.float32) / float(H + 1e-6)

    max_strip = int(0.12 * W)

    left_w = 0
    streak = 0
    for i in range(W):
        if col_ratio[i] >= 0.65:
            streak += 1
            left_w = i + 1
        else:
            if streak >= 3:
                break
            streak = 0
            left_w = 0

    right_w = 0
    streak = 0
    for k, i in enumerate(range(W - 1, -1, -1)):
        if col_ratio[i] >= 0.65:
            streak += 1
            right_w = k + 1
        else:
            if streak >= 3:
                break
            streak = 0
            right_w = 0

    left_w = min(left_w, max_strip)
    right_w = min(right_w, max_strip)

    out = mask.copy()
    if left_w > 0:
        out[:, :left_w] = 0
    if right_w > 0:
        out[:, W - right_w:] = 0
    return out


def projection_boxes(mask):
    H, W = mask.shape[:2]
    col_sum = np.sum(mask > 0, axis=0).astype(np.float32)
    peak = float(np.max(col_sum)) if col_sum.size else 0.0
    if peak <= 0:
        return []

    col_norm = col_sum / (peak + 1e-6)
    threshold = 0.05

    splits = []
    in_char = False
    start = 0

    for i, val in enumerate(col_norm):
        if val > threshold and not in_char:
            start = i
            in_char = True
        elif val <= threshold and in_char:
            splits.append((start, i))
            in_char = False

    if in_char:
        splits.append((start, W))

    boxes = []
    for (x0, x1) in splits:
        width = x1 - x0

        if width < 3:
            continue
        if width > 0.85 * W:
            continue

        col_region = mask[:, x0:x1]
        rows = np.where(np.sum(col_region > 0, axis=1) > 0)[0]

        if len(rows) == 0:
            continue

        y0 = int(rows[0])
        y1 = int(rows[-1] + 1)
        h = y1 - y0

        if h < 0.28 * H:
            continue

        boxes.append((x0, y0, width, h))

    return sorted(boxes, key=lambda b: b[0])


def contour_boxes(mask):
    H, W = mask.shape[:2]
    cnts, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    boxes = []
    for c in cnts:
        x, y, w, h = cv2.boundingRect(c)

        if w * h < 20:
            continue
        if h < 0.28 * H:
            continue
        if w > 0.85 * W:
            continue

        fill = float(cv2.contourArea(c)) / float((w * h) + 1e-6)
        if fill < 0.08:
            continue

        boxes.append((x, y, w, h))

    return sorted(boxes, key=lambda b: b[0])


def _tight_box_from_roi(roi, x_off, y_off):
    ys, xs = np.where(roi > 0)
    if len(xs) == 0 or len(ys) == 0:
        return None
    x0 = int(xs.min())
    x1 = int(xs.max() + 1)
    y0 = int(ys.min())
    y1 = int(ys.max() + 1)
    return (x_off + x0, y_off + y0, x1 - x0, y1 - y0)


def split_wide_box_once(mask, box, valley_rel=0.65):
    """
    One split attempt inside a wide merged blob.
    """
    x, y, w, h = box
    roi = mask[y:y+h, x:x+w]
    if roi.size == 0 or w < 10:
        return [box]

    col = np.sum(roi > 0, axis=0).astype(np.float32)
    peak = float(np.max(col)) if col.size else 0.0
    if peak <= 0:
        return [box]

    col = np.convolve(col, np.ones(5) / 5.0, mode="same")

    l = max(2, int(0.18 * w))
    r = min(w - 2, int(0.82 * w))
    if r <= l:
        return [box]

    best_s = None
    best_val = None

    for s in range(l, r):
        valley = float(col[s])
        left_peak = float(np.max(col[:s])) if s > 0 else 0.0
        right_peak = float(np.max(col[s:])) if s < w else 0.0

        if left_peak < 1e-6 or right_peak < 1e-6:
            continue

        if valley <= valley_rel * min(left_peak, right_peak):
            if best_val is None or valley < best_val:
                best_val = valley
                best_s = s

    if best_s is None:
        return [box]

    s = int(best_s)
    left_roi = roi[:, :s]
    right_roi = roi[:, s:]

    b1 = _tight_box_from_roi(left_roi, x, y)
    b2 = _tight_box_from_roi(right_roi, x + s, y)

    out = []
    for b in (b1, b2):
        if b is None:
            continue
        bx, by, bw, bh = b
        if bw >= 3 and bh >= int(0.28 * mask.shape[0]):
            out.append((bx, by, bw, bh))

    return out if len(out) == 2 else [box]


def recursive_split_boxes(mask, boxes, merge_w_factor=1.20, max_depth=6):
    """
    Recursively split merged letters like PLACE / LAB.
    """
    if not boxes:
        return []

    out = sorted(boxes, key=lambda b: b[0])

    for _ in range(max_depth):
        widths = np.array([b[2] for b in out], dtype=np.float32)
        median_w = float(np.median(widths)) if len(widths) else 0.0
        if median_w <= 0:
            break

        changed = False
        new_out = []

        for b in out:
            if b[2] > merge_w_factor * median_w:
                split = split_wide_box_once(mask, b, valley_rel=0.65)
                if len(split) == 2:
                    new_out.extend(split)
                    changed = True
                else:
                    new_out.append(b)
            else:
                new_out.append(b)

        out = sorted(new_out, key=lambda b: b[0])

        if not changed:
            break

    return out


def infer_spaces_from_boxes(boxes):
    """
    Runtime-style space inference from large gaps.
    Returns a list of booleans of length len(boxes)-1 telling whether a space
    should be inserted after each character.
    """
    if len(boxes) < 2:
        return []

    widths = np.array([b[2] for b in boxes], dtype=np.float32)
    median_w = float(np.median(widths)) if len(widths) else 0.0

    gaps = []
    for i in range(len(boxes) - 1):
        x, y, w, h = boxes[i]
        x2, y2, w2, h2 = boxes[i + 1]
        gaps.append(max(0, x2 - (x + w)))

    median_gap = float(np.median(gaps)) if gaps else 0.0
    gap_thr = max(8.0, 1.35 * max(median_gap, 0.25 * median_w))

    return [g > gap_thr for g in gaps]

# 6
def segment_visible_chars_from_line(line_bgr, debug=False):
    """
    Segment only VISIBLE characters.
    Spaces are not segmented here.
    """
    hsv = cv2.cvtColor(line_bgr, cv2.COLOR_BGR2HSV)

    lower_blue = np.array([90, 40, 35])
    upper_blue = np.array([150, 255, 255])
    mask = cv2.inRange(hsv, lower_blue, upper_blue)

    mask = clean_blue_mask(mask)
    mask = strip_edges_if_needed(mask)

    boxes = projection_boxes(mask)
    if len(boxes) == 0:
        boxes = contour_boxes(mask)

    boxes = recursive_split_boxes(mask, boxes, merge_w_factor=1.20, max_depth=6)

    H, W = mask.shape[:2]
    crops = []

    for x, y, w, h in boxes:
        pad = max(2, int(0.18 * max(w, h)))
        x0 = max(0, x - pad)
        y0 = max(0, y - pad)
        x1 = min(W, x + w + pad)
        y1 = min(H, y + h + pad)

        crop = line_bgr[y0:y1, x0:x1]
        processed = preprocess_training_crop(crop)
        crops.append(processed)

    if debug:
        dbg = cv2.cvtColor(mask, cv2.COLOR_GRAY2BGR)
        for x, y, w, h in boxes:
            cv2.rectangle(dbg, (x, y), (x + w, y + h), (0, 255, 0), 2)
        return crops, mask, dbg, boxes

    return crops, mask, None, boxes


def segment_real_line_image(line_bgr, debug=False):
    """
    Same logic as generated line segmentation.
    """
    hsv = cv2.cvtColor(line_bgr, cv2.COLOR_BGR2HSV)

    lower_blue = np.array([90, 40, 35])
    upper_blue = np.array([150, 255, 255])
    mask = cv2.inRange(hsv, lower_blue, upper_blue)

    mask = clean_blue_mask(mask)
    mask = strip_edges_if_needed(mask)

    boxes = projection_boxes(mask)
    if len(boxes) == 0:
        boxes = contour_boxes(mask)

    boxes = recursive_split_boxes(mask, boxes, merge_w_factor=1.20, max_depth=6)

    H, W = mask.shape[:2]
    crops = []

    for x, y, w, h in boxes:
        pad = max(2, int(0.18 * max(w, h)))
        x0 = max(0, x - pad)
        y0 = max(0, y - pad)
        x1 = min(W, x + w + pad)
        y1 = min(H, y + h + pad)

        crop = line_bgr[y0:y1, x0:x1]
        processed = preprocess_training_crop(crop)
        crops.append(processed)

    if debug:
        dbg = cv2.cvtColor(mask, cv2.COLOR_GRAY2BGR)
        for x, y, w, h in boxes:
            cv2.rectangle(dbg, (x, y), (x + w, y + h), (0, 255, 0), 2)
        return crops, mask, dbg, boxes

    return crops, mask, None, boxes

sample_file = random.choice(files)
sample_path = os.path.join(IMAGE_DIR, sample_file)

img = cv2.imread(sample_path)
warped, mask, dbg = detect_and_warp_sign(img, debug=True)

print("sample file:", sample_file)
print("parsed:", parse_filename(sample_file))

plt.figure(figsize=(15, 5))
plt.subplot(1, 3, 1)
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.title("Original")
plt.axis("off")

plt.subplot(1, 3, 2)
plt.imshow(mask, cmap="gray")
plt.title("Blue mask")
plt.axis("off")

plt.subplot(1, 3, 3)
plt.imshow(cv2.cvtColor(dbg, cv2.COLOR_BGR2RGB))
plt.title("Detected sign")
plt.axis("off")
plt.show()

if warped is not None:
    top_line, bottom_line = split_sign_lines(warped)

    idx, clue_type, clue_value, variant = parse_filename(sample_file)

    top_crops, top_mask, top_dbg, top_boxes = segment_visible_chars_from_line(top_line, debug=True)
    bot_crops, bot_mask, bot_dbg, bot_boxes = segment_visible_chars_from_line(bottom_line, debug=True)

    print("Top expected:", clue_type, "detected boxes:", len(top_boxes))
    print("Bottom expected:", repr(clue_value), "detected visible boxes:", len(bot_boxes))
    print("Bottom expected visible count:", len(clue_value.replace(" ", "")))
    print("Space pattern inferred from boxes:", infer_spaces_from_boxes(bot_boxes))

    plt.figure(figsize=(12, 5))
    plt.subplot(2, 2, 1)
    plt.imshow(cv2.cvtColor(top_dbg, cv2.COLOR_BGR2RGB))
    plt.title("Top debug")
    plt.axis("off")

    plt.subplot(2, 2, 2)
    plt.imshow(top_mask, cmap="gray")
    plt.title("Top mask")
    plt.axis("off")

    plt.subplot(2, 2, 3)
    plt.imshow(cv2.cvtColor(bot_dbg, cv2.COLOR_BGR2RGB))
    plt.title("Bottom debug")
    plt.axis("off")

    plt.subplot(2, 2, 4)
    plt.imshow(bot_mask, cmap="gray")
    plt.title("Bottom mask")
    plt.axis("off")
    plt.show()
else:
    print("Failed to warp sign")

X = []
y = []

good = 0
bad = 0
bad_examples = []

for fname in files:
    path = os.path.join(IMAGE_DIR, fname)
    img = cv2.imread(path)

    if img is None:
        bad += 1
        bad_examples.append((fname, "imread failed"))
        continue

    _, clue_type, clue_value, _ = parse_filename(fname)

    warped, _, _ = detect_and_warp_sign(img, debug=False)
    if warped is None:
        bad += 1
        bad_examples.append((fname, "warp failed"))
        continue

    top_line, bottom_line = split_sign_lines(warped)

    top_crops, _, _, top_boxes = segment_visible_chars_from_line(top_line, debug=False)
    bot_crops, _, _, bot_boxes = segment_visible_chars_from_line(bottom_line, debug=False)

    top_target = clue_type
    bottom_target_full = clue_value
    bottom_target_visible = clue_value.replace(" ", "")

    if len(top_crops) != len(top_target):
        bad += 1
        bad_examples.append((fname, f"top count mismatch: got {len(top_crops)} expected {len(top_target)}"))
        continue

    if len(bot_crops) != len(bottom_target_visible):
        bad += 1
        bad_examples.append((fname, f"bottom visible count mismatch: got {len(bot_crops)} expected {len(bottom_target_visible)}"))
        continue

    for crop, ch in zip(top_crops, top_target):
        if ch in CLASS_TO_IDX:
            X.append(crop)
            y.append(CLASS_TO_IDX[ch])

    for crop, ch in zip(bot_crops, bottom_target_visible):
        if ch in CLASS_TO_IDX:
            X.append(crop)
            y.append(CLASS_TO_IDX[ch])

    for ch in bottom_target_full:
        if ch == " ":
            X.append(make_space_crop())
            y.append(CLASS_TO_IDX[" "])

    good += 1

X = np.array(X, dtype=np.float32) / 255.0
X = X[..., None]
y = np.array(y, dtype=np.int64)

print("good generated images:", good)
print("bad generated images:", bad)
print("X shape:", X.shape)
print("y shape:", y.shape)
print("unique classes:", len(set(y.tolist())))
print("some bad examples:", bad_examples[:15])

counts = np.bincount(y, minlength=len(CLASSES))

print("total samples:", len(y))
print("min per class:", counts.min())
print("missing classes:", [DISPLAY_CLASSES[i] for i in range(len(CLASSES)) if counts[i] == 0])

plt.figure(figsize=(14, 4))
plt.bar(DISPLAY_CLASSES, counts)
plt.title("Generated training character distribution (including space)")
plt.xlabel("Class")
plt.ylabel("Count")
plt.xticks(rotation=90)
plt.grid(axis="y", linestyle="--", alpha=0.5)
plt.show()

plt.figure(figsize=(12, 8))
for i in range(16):
    idx = random.randint(0, len(X) - 1)
    plt.subplot(4, 4, i + 1)
    plt.imshow(X[idx].squeeze(), cmap="gray")
    plt.title(DISPLAY_CLASSES[y[idx]])
    plt.axis("off")
plt.tight_layout()
plt.show()

num_classes = len(CLASSES)
Y = tf.keras.utils.to_categorical(y, num_classes)

X_train, X_val, Y_train, Y_val, y_train_idx, y_val_idx = train_test_split(
    X, Y, y,
    test_size=0.2,
    random_state=0,
    stratify=y
)

print("Train:", X_train.shape, Y_train.shape)
print("Val:  ", X_val.shape, Y_val.shape)

class_weights_arr = compute_class_weight(
    class_weight="balanced",
    classes=np.unique(y_train_idx),
    y=y_train_idx
)
class_weights = {int(c): float(w) for c, w in zip(np.unique(y_train_idx), class_weights_arr)}

print("class weights:")
for k in sorted(class_weights.keys()):
    print(DISPLAY_CLASSES[k], "->", round(class_weights[k], 3))

class RandomBrightnessContrast(tf.keras.layers.Layer):
    def __init__(self, brightness=0.08, contrast=0.10):
        super().__init__()
        self.brightness = brightness
        self.contrast = contrast

    def call(self, x, training=None):
        if not training:
            return x

        b = tf.random.uniform([], -self.brightness, self.brightness)
        c = tf.random.uniform([], 1.0 - self.contrast, 1.0 + self.contrast)

        x = x * c + b
        x = tf.clip_by_value(x, 0.0, 1.0)
        return x


data_augmentation = tf.keras.Sequential([
    tf.keras.layers.RandomRotation(0.03),
    tf.keras.layers.RandomTranslation(0.05, 0.05),
    tf.keras.layers.RandomZoom(0.08),
    RandomBrightnessContrast(0.08, 0.10),
], name="data_augmentation")


model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(32, 32, 1)),

    data_augmentation,

    tf.keras.layers.Conv2D(32, 3, padding="same", use_bias=False),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.ReLU(),
    tf.keras.layers.MaxPool2D(),

    tf.keras.layers.Conv2D(64, 3, padding="same", use_bias=False),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.ReLU(),
    tf.keras.layers.MaxPool2D(),

    tf.keras.layers.Conv2D(128, 3, padding="same", use_bias=False),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.ReLU(),
    tf.keras.layers.MaxPool2D(),

    tf.keras.layers.Conv2D(128, 3, padding="same", use_bias=False),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.ReLU(),

    tf.keras.layers.GlobalAveragePooling2D(),
    tf.keras.layers.Dense(256, activation="relu"),
    tf.keras.layers.Dropout(0.35),
    tf.keras.layers.Dense(num_classes, activation="softmax"),
])

model.compile(
    optimizer=tf.keras.optimizers.Adam(1e-4),
    loss=tf.keras.losses.CategoricalCrossentropy(label_smoothing=0.05),
    metrics=["accuracy"]
)

model.summary()

# 11
callbacks = [
    tf.keras.callbacks.EarlyStopping(
        monitor="val_accuracy",
        patience=5,
        restore_best_weights=True
    ),
    tf.keras.callbacks.ReduceLROnPlateau(
        monitor="val_loss",
        factor=0.5,
        patience=2,
        min_lr=1e-6,
        verbose=1
    )
]

hist = model.fit(
    X_train, Y_train,
    validation_data=(X_val, Y_val),
    epochs=30,
    batch_size=64,
    callbacks=callbacks,
    class_weight=class_weights,
    verbose=1
)

plt.figure()
plt.plot(hist.history["loss"], label="train loss")
plt.plot(hist.history["val_loss"], label="val loss")
plt.xlabel("epoch")
plt.ylabel("loss")
plt.legend()
plt.show()

plt.figure()
plt.plot(hist.history["accuracy"], label="train acc")
plt.plot(hist.history["val_accuracy"], label="val acc")
plt.xlabel("epoch")
plt.ylabel("accuracy")
plt.legend()
plt.show()

pred_probs = model.predict(X_val, verbose=0)
pred_labels = np.argmax(pred_probs, axis=1)
true_labels = np.argmax(Y_val, axis=1)

accuracy = np.mean(pred_labels == true_labels)
print("Validation accuracy:", accuracy)

cm = confusion_matrix(true_labels, pred_labels)

plt.figure(figsize=(12, 10))
plt.imshow(cm, interpolation="nearest")
plt.colorbar()
plt.xticks(range(len(DISPLAY_CLASSES)), DISPLAY_CLASSES, rotation=90)
plt.yticks(range(len(DISPLAY_CLASSES)), DISPLAY_CLASSES)
plt.xlabel("Predicted")
plt.ylabel("True")
plt.title("Generated-data confusion matrix")
plt.tight_layout()
plt.show()

plt.figure(figsize=(12, 8))
for i in range(16):
    plt.subplot(4, 4, i + 1)
    plt.imshow(X_val[i].squeeze(), cmap="gray")
    plt.title(f"T:{DISPLAY_CLASSES[true_labels[i]]} P:{DISPLAY_CLASSES[pred_labels[i]]}")
    plt.axis("off")
plt.tight_layout()
plt.show()

model.save(BASE_MODEL_KERAS_PATH)
print("saved keras model:", BASE_MODEL_KERAS_PATH)

converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

with open(BASE_MODEL_TFLITE_PATH, "wb") as f:
    f.write(tflite_model)

print("saved tflite model:", BASE_MODEL_TFLITE_PATH)

with open(CLASSES_PATH, "w") as f:
    json.dump(CLASSES, f)

print("saved class list:", CLASSES_PATH)

sample_real = random.choice(real_files)
sample_real_path = os.path.join(REAL_LINE_DIR, sample_real)
sample_img = cv2.imread(sample_real_path)

sample_text = parse_line_filename(sample_real)
real_crops, real_mask, real_dbg, real_boxes = segment_real_line_image(sample_img, debug=True)

print("sample file:", sample_real)
print("expected text:", repr(sample_text))
print("visible-only expected:", sample_text.replace(" ", ""))
print("detected boxes:", len(real_boxes))
print("space pattern inferred from boxes:", infer_spaces_from_boxes(real_boxes))

plt.figure(figsize=(12, 4))
plt.subplot(1, 3, 1)
plt.imshow(cv2.cvtColor(sample_img, cv2.COLOR_BGR2RGB))
plt.title("Original")
plt.axis("off")

plt.subplot(1, 3, 2)
plt.imshow(real_mask, cmap="gray")
plt.title("Mask")
plt.axis("off")

plt.subplot(1, 3, 3)
plt.imshow(cv2.cvtColor(real_dbg, cv2.COLOR_BGR2RGB))
plt.title("Boxes")
plt.axis("off")
plt.show()

plt.figure(figsize=(12, 3))
for i, crop in enumerate(real_crops[:10]):
    plt.subplot(1, min(10, len(real_crops)), i + 1)
    plt.imshow(crop, cmap="gray")
    plt.axis("off")
plt.tight_layout()
plt.show()

X_real = []
y_real = []

good_real = 0
bad_real = 0
bad_real_examples = []

for fname in real_files:
    path = os.path.join(REAL_LINE_DIR, fname)
    img = cv2.imread(path)

    if img is None:
        bad_real += 1
        bad_real_examples.append((fname, "imread failed"))
        continue

    text_full = parse_line_filename(fname)
    text_visible = text_full.replace(" ", "")

    crops, _, _, boxes = segment_real_line_image(img, debug=False)

    if len(crops) != len(text_visible):
        bad_real += 1
        bad_real_examples.append((fname, f"visible count mismatch: got {len(crops)} expected {len(text_visible)}"))
        continue

    for crop, ch in zip(crops, text_visible):
        if ch in CLASS_TO_IDX:
            X_real.append(crop)
            y_real.append(CLASS_TO_IDX[ch])

    for ch in text_full:
        if ch == " ":
            X_real.append(make_space_crop())
            y_real.append(CLASS_TO_IDX[" "])

    good_real += 1

X_real = np.array(X_real, dtype=np.float32) / 255.0
X_real = X_real[..., None]
y_real = np.array(y_real, dtype=np.int64)

print("good real line images:", good_real)
print("bad real line images:", bad_real)
print("X_real shape:", X_real.shape)
print("y_real shape:", y_real.shape)
print("some bad real examples:", bad_real_examples[:20])

# 16
print("first 20 bad examples:")
for ex in bad_real_examples[:20]:
    print(ex)

failed = bad_real_examples[:12]

for fname, reason in failed:
    path = os.path.join(REAL_LINE_DIR, fname)
    img = cv2.imread(path)
    if img is None:
        continue

    text = parse_line_filename(fname)
    crops, mask, dbg, boxes = segment_real_line_image(img, debug=True)

    print("FILE:", fname)
    print("TEXT:", repr(text))
    print("VISIBLE TEXT:", text.replace(" ", ""))
    print("REASON:", reason)
    print("BOX COUNT:", len(boxes))
    print("-" * 40)

    plt.figure(figsize=(12, 4))
    plt.subplot(1, 3, 1)
    plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
    plt.title(f"Original: {fname}")
    plt.axis("off")

    plt.subplot(1, 3, 2)
    plt.imshow(mask, cmap="gray")
    plt.title("Mask")
    plt.axis("off")

    plt.subplot(1, 3, 3)
    plt.imshow(cv2.cvtColor(dbg, cv2.COLOR_BGR2RGB))
    plt.title(f"Boxes ({len(boxes)})")
    plt.axis("off")

    plt.show()

counts_real = np.bincount(y_real, minlength=len(CLASSES))

print("total real char samples:", len(y_real))
print("min per class:", counts_real.min())
print("missing classes:", [DISPLAY_CLASSES[i] for i in range(len(CLASSES)) if counts_real[i] == 0])

plt.figure(figsize=(14, 4))
plt.bar(DISPLAY_CLASSES, counts_real)
plt.title("Real fine-tuning character distribution (including space)")
plt.xlabel("Class")
plt.ylabel("Count")
plt.xticks(rotation=90)
plt.grid(axis="y", linestyle="--", alpha=0.5)
plt.show()

plt.figure(figsize=(12, 8))
for i in range(16):
    idx = random.randint(0, len(X_real) - 1)
    plt.subplot(4, 4, i + 1)
    plt.imshow(X_real[idx].squeeze(), cmap="gray")
    plt.title(DISPLAY_CLASSES[y_real[idx]])
    plt.axis("off")
plt.tight_layout()
plt.show()

real_class_weights_arr = compute_class_weight(
    class_weight="balanced",
    classes=np.unique(y_real),
    y=y_real
)
real_class_weights = {int(c): float(w) for c, w in zip(np.unique(y_real), real_class_weights_arr)}

print("real fine-tune class weights:")
for k in sorted(real_class_weights.keys()):
    print(DISPLAY_CLASSES[k], "->", round(real_class_weights[k], 3))

Y_real = tf.keras.utils.to_categorical(y_real, len(CLASSES))

model.compile(
    optimizer=tf.keras.optimizers.Adam(5e-5),
    loss=tf.keras.losses.CategoricalCrossentropy(label_smoothing=0.03),
    metrics=["accuracy"]
)

callbacks_real = [
    tf.keras.callbacks.EarlyStopping(
        monitor="val_accuracy",
        patience=4,
        restore_best_weights=True
    ),
    tf.keras.callbacks.ReduceLROnPlateau(
        monitor="val_loss",
        factor=0.5,
        patience=2,
        min_lr=1e-6,
        verbose=1
    )
]

hist_real = model.fit(
    X_real, Y_real,
    validation_split=0.15,
    epochs=15,
    batch_size=32,
    callbacks=callbacks_real,
    class_weight=real_class_weights,
    verbose=1
)

plt.figure()
plt.plot(hist_real.history["loss"], label="train loss")
plt.plot(hist_real.history["val_loss"], label="val loss")
plt.xlabel("epoch")
plt.ylabel("loss")
plt.legend()
plt.show()

plt.figure()
plt.plot(hist_real.history["accuracy"], label="train acc")
plt.plot(hist_real.history["val_accuracy"], label="val acc")
plt.xlabel("epoch")
plt.ylabel("accuracy")
plt.legend()
plt.show()

model.save(FINETUNED_MODEL_KERAS_PATH)
print("saved keras model:", FINETUNED_MODEL_KERAS_PATH)

converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

with open(FINETUNED_MODEL_TFLITE_PATH, "wb") as f:
    f.write(tflite_model)

print("saved tflite model:", FINETUNED_MODEL_TFLITE_PATH)

with open(CLASSES_PATH, "w") as f:
    json.dump(CLASSES, f)

print("saved class list:", CLASSES_PATH)

# 20
interpreter = tf.lite.Interpreter(model_path=FINETUNED_MODEL_TFLITE_PATH)
interpreter.allocate_tensors()

input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

print("Input details:", input_details)
print("Output details:", output_details)

x_test = X_real[0:1].astype(np.float32)

interpreter.set_tensor(input_details[0]["index"], x_test)
interpreter.invoke()
output = interpreter.get_tensor(output_details[0]["index"])

pred_idx = int(np.argmax(output))
true_idx = int(y_real[0])

print("True:", DISPLAY_CLASSES[true_idx])
print("Pred:", DISPLAY_CLASSES[pred_idx])
print("Confidence:", float(np.max(output)))