# -*- coding: utf-8 -*-
"""ENPH353_actual_finalCNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UOo-jz8dKZzd2AG7B3AO8kdHNAALufRe
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import json
import random
import cv2
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.utils.class_weight import compute_class_weight

IMAGE_DIR = "/content/drive/MyDrive/353_data/images/train"
REAL_LINE_DIR = "/content/drive/MyDrive/353_photos"

# 37 classes now: 0-9, A-Z, and SPACE
SPACE_TOKEN = " "
CLASSES = list("0123456789") + list("ABCDEFGHIJKLMNOPQRSTUVWXYZ") + [SPACE_TOKEN]
DISPLAY_CLASSES = [c if c != " " else "␠" for c in CLASSES]

CLASS_TO_IDX = {c: i for i, c in enumerate(CLASSES)}
IDX_TO_CLASS = {i: c for i, c in enumerate(CLASSES)}

print("num classes:", len(CLASSES))
print("classes:", DISPLAY_CLASSES)

files = sorted([
    f for f in os.listdir(IMAGE_DIR)
    if f.lower().endswith((".png", ".jpg", ".jpeg"))
])

print("num files:", len(files))
print(files[:10])

def normalize_space_text(text: str) -> str:
    """
    Support both conventions:
    - actual spaces
    - ~ meaning space
    """
    return text.replace("~", " ").upper()


def parse_filename(fname):
    """
    Expected training filename style:
    <index>_<clue_type>_<clue_value>_<variant>.png

    clue_value may contain ~ to indicate spaces.
    """
    stem = os.path.splitext(fname)[0]
    parts = stem.split("_")

    index = parts[0]
    clue_type = normalize_space_text(parts[1])
    variant = parts[-1]
    clue_value = normalize_space_text("_".join(parts[2:-1]))

    return index, clue_type, clue_value, variant


for f in files[:10]:
    print(f, "->", parse_filename(f))

sample_file = random.choice(files)
sample_path = os.path.join(IMAGE_DIR, sample_file)

img = cv2.imread(sample_path)
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

print("sample file:", sample_file)
print("parsed:", parse_filename(sample_file))

plt.figure(figsize=(8, 8))
plt.imshow(img_rgb)
plt.axis("off")
plt.title(sample_file)
plt.show()

# 6
def order_points(pts):
    pts = np.array(pts, dtype=np.float32)
    s = pts.sum(axis=1)
    diff = np.diff(pts, axis=1)

    top_left = pts[np.argmin(s)]
    bottom_right = pts[np.argmax(s)]
    top_right = pts[np.argmin(diff)]
    bottom_left = pts[np.argmax(diff)]

    return np.array([top_left, top_right, bottom_right, bottom_left], dtype=np.float32)


def four_point_transform(image, pts, out_w=400, out_h=600):
    rect = order_points(pts)
    dst = np.array([
        [0, 0],
        [out_w - 1, 0],
        [out_w - 1, out_h - 1],
        [0, out_h - 1]
    ], dtype=np.float32)

    M = cv2.getPerspectiveTransform(rect, dst)
    warped = cv2.warpPerspective(image, M, (out_w, out_h))
    return warped


def detect_and_warp_sign(img_bgr, debug=False):
    hsv = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2HSV)

    lower_blue = np.array([100, 100, 50])
    upper_blue = np.array([140, 255, 255])
    mask = cv2.inRange(hsv, lower_blue, upper_blue)

    kernel = np.ones((5, 5), np.uint8)
    mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernel, iterations=2)
    mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, kernel, iterations=1)

    cnts, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    if not cnts:
        return None, mask, None

    cnts = sorted(cnts, key=cv2.contourArea, reverse=True)

    chosen_quad = None
    for c in cnts[:10]:
        peri = cv2.arcLength(c, True)
        approx = cv2.approxPolyDP(c, 0.03 * peri, True)

        if len(approx) == 4:
            chosen_quad = approx.reshape(4, 2)
            break

    if chosen_quad is None:
        c = cnts[0]
        rect = cv2.minAreaRect(c)
        box = cv2.boxPoints(rect)
        chosen_quad = box.astype(int)

    warped = four_point_transform(img_bgr, chosen_quad, out_w=400, out_h=300)

    if debug:
        dbg = img_bgr.copy()
        cv2.drawContours(dbg, [chosen_quad.astype(int)], -1, (0, 255, 0), 3)
        return warped, mask, dbg

    return warped, mask, None

sample_file = random.choice(files)
sample_path = os.path.join(IMAGE_DIR, sample_file)
img = cv2.imread(sample_path)

warped, mask, dbg = detect_and_warp_sign(img, debug=True)

print(sample_file)
print(parse_filename(sample_file))

plt.figure(figsize=(15, 5))
plt.subplot(1, 3, 1)
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.title("Original")
plt.axis("off")

plt.subplot(1, 3, 2)
plt.imshow(mask, cmap="gray")
plt.title("Blue mask")
plt.axis("off")

plt.subplot(1, 3, 3)
plt.imshow(cv2.cvtColor(dbg, cv2.COLOR_BGR2RGB))
plt.title("Detected sign")
plt.axis("off")
plt.show()

if warped is not None:
    plt.figure(figsize=(6, 5))
    plt.imshow(cv2.cvtColor(warped, cv2.COLOR_BGR2RGB))
    plt.title("Warped sign")
    plt.axis("off")
    plt.show()
else:
    print("Failed to warp sign")

# 8
def split_sign_lines(warped_bgr):
    h, w = warped_bgr.shape[:2]

    top_line = warped_bgr[int(0.10 * h):int(0.38 * h), int(0.42 * w):int(0.92 * w)]
    bottom_line = warped_bgr[int(0.58 * h):int(0.88 * h), int(0.08 * w):int(0.92 * w)]

    return top_line, bottom_line


top_line, bottom_line = split_sign_lines(warped)

plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.imshow(cv2.cvtColor(top_line, cv2.COLOR_BGR2RGB))
plt.title("Top line")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(cv2.cvtColor(bottom_line, cv2.COLOR_BGR2RGB))
plt.title("Bottom line")
plt.axis("off")
plt.show()

def preprocess_training_crop(crop_bgr):
    gray = cv2.cvtColor(crop_bgr, cv2.COLOR_BGR2GRAY)

    gray = cv2.equalizeHist(gray)
    gray = cv2.GaussianBlur(gray, (3, 3), 0)

    _, bw = cv2.threshold(
        gray, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU
    )

    h, w = bw.shape[:2]
    side = max(h, w) + 10

    canvas = np.zeros((side, side), dtype=np.uint8)
    y_off = (side - h) // 2
    x_off = (side - w) // 2
    canvas[y_off:y_off + h, x_off:x_off + w] = bw

    canvas = cv2.resize(canvas, (40, 40), interpolation=cv2.INTER_AREA)
    canvas = cv2.resize(canvas, (32, 32), interpolation=cv2.INTER_AREA)

    return canvas


def make_space_crop():
    """
    Explicit synthetic crop for the SPACE class.
    Keep it blank because a space should correspond to no visible character.
    """
    return np.zeros((32, 32), dtype=np.uint8)

# 10
def segment_visible_chars_from_line(line_bgr, debug=False):
    """
    Segment only visible characters.
    Spaces are NOT segmented here.
    Spaces will be added as synthetic blank samples during dataset assembly.
    """
    hsv = cv2.cvtColor(line_bgr, cv2.COLOR_BGR2HSV)

    lower_blue = np.array([90, 40, 40])
    upper_blue = np.array([150, 255, 255])
    mask = cv2.inRange(hsv, lower_blue, upper_blue)

    mask = cv2.medianBlur(mask, 3)
    kernel = np.ones((2, 2), np.uint8)
    mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, kernel, iterations=1)

    H, W = mask.shape[:2]

    # Projection-based splitting works better for these line images
    col_sum = np.sum(mask > 0, axis=0).astype(float)
    col_sum = col_sum / (np.max(col_sum) + 1e-6)

    threshold = 0.05
    splits = []
    in_char = False
    start = 0

    for i, val in enumerate(col_sum):
        if val > threshold and not in_char:
            start = i
            in_char = True
        elif val <= threshold and in_char:
            end = i
            splits.append((start, end))
            in_char = False

    if in_char:
        splits.append((start, W))

    boxes = []
    for (x0, x1) in splits:
        width = x1 - x0

        if width < 3:
            continue
        if width > 0.35 * W:
            continue

        col_region = mask[:, x0:x1]
        rows = np.where(np.sum(col_region > 0, axis=1) > 0)[0]

        if len(rows) == 0:
            continue

        y0 = rows[0]
        y1 = rows[-1]

        w = width
        h = y1 - y0 + 1

        if h < 0.30 * H:
            continue

        boxes.append((x0, y0, w, h))

    # Fallback to contours if projection fails
    if len(boxes) == 0:
        cnts, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        for c in cnts:
            x, y, w, h = cv2.boundingRect(c)

            if w * h < 20:
                continue
            if h < 0.30 * H:
                continue
            if w > 0.35 * W:
                continue

            boxes.append((x, y, w, h))

    boxes = sorted(boxes, key=lambda b: b[0])

    crops = []
    for x, y, w, h in boxes:
        pad = max(2, int(0.12 * max(w, h)))
        x0 = max(0, x - pad)
        y0 = max(0, y - pad)
        x1 = min(W, x + w + pad)
        y1 = min(H, y + h + pad)

        crop = line_bgr[y0:y1, x0:x1]
        processed = preprocess_training_crop(crop)
        crops.append(processed)

    if debug:
        dbg = cv2.cvtColor(mask, cv2.COLOR_GRAY2BGR)
        for x, y, w, h in boxes:
            cv2.rectangle(dbg, (x, y), (x + w, y + h), (0, 255, 0), 2)
        return crops, mask, dbg, boxes

    return crops, mask, None, boxes

idx, clue_type, clue_value, variant = parse_filename(sample_file)

top_crops, top_mask, top_dbg, top_boxes = segment_visible_chars_from_line(top_line, debug=True)
bot_crops, bot_mask, bot_dbg, bot_boxes = segment_visible_chars_from_line(bottom_line, debug=True)

print("Top expected:", clue_type, "detected boxes:", len(top_boxes))
print("Bottom expected:", clue_value, "detected visible boxes:", len(bot_boxes))
print("Bottom expected visible count:", len(clue_value.replace(" ", "")))

plt.figure(figsize=(12, 4))
plt.subplot(2, 2, 1)
plt.imshow(cv2.cvtColor(top_dbg, cv2.COLOR_BGR2RGB))
plt.title("Top debug")
plt.axis("off")

plt.subplot(2, 2, 2)
plt.imshow(top_mask, cmap="gray")
plt.title("Top mask")
plt.axis("off")

plt.subplot(2, 2, 3)
plt.imshow(cv2.cvtColor(bot_dbg, cv2.COLOR_BGR2RGB))
plt.title("Bottom debug")
plt.axis("off")

plt.subplot(2, 2, 4)
plt.imshow(bot_mask, cmap="gray")
plt.title("Bottom mask")
plt.axis("off")
plt.show()

print("Top target len:", len(clue_type))
print("Bottom target len (with spaces):", len(clue_value))
print("Bottom target len (visible only):", len(clue_value.replace(" ", "")))

# Segmegnt blue chars from one line, 12
X = []
y = []

good = 0
bad = 0
bad_examples = []

for fname in files:
    path = os.path.join(IMAGE_DIR, fname)
    img = cv2.imread(path)
    if img is None:
        bad += 1
        bad_examples.append((fname, "imread failed"))
        continue

    _, clue_type, clue_value, _ = parse_filename(fname)

    warped, mask, dbg = detect_and_warp_sign(img, debug=False)
    if warped is None:
        bad += 1
        bad_examples.append((fname, "warp failed"))
        continue

    top_line, bottom_line = split_sign_lines(warped)

    top_crops, _, _, top_boxes = segment_visible_chars_from_line(top_line, debug=False)
    bot_crops, _, _, bot_boxes = segment_visible_chars_from_line(bottom_line, debug=False)

    top_target = clue_type
    bottom_target_full = clue_value
    bottom_target_visible = clue_value.replace(" ", "")

    if len(top_crops) != len(top_target):
        bad += 1
        bad_examples.append((fname, f"top count mismatch: got {len(top_crops)} expected {len(top_target)}"))
        continue

    if len(bot_crops) != len(bottom_target_visible):
        bad += 1
        bad_examples.append((fname, f"bottom visible count mismatch: got {len(bot_crops)} expected {len(bottom_target_visible)}"))
        continue

    # Top line: always visible chars
    for crop, ch in zip(top_crops, top_target):
        if ch not in CLASS_TO_IDX:
            continue
        X.append(crop)
        y.append(CLASS_TO_IDX[ch])

    # Bottom line: visible chars only
    for crop, ch in zip(bot_crops, bottom_target_visible):
        if ch not in CLASS_TO_IDX:
            continue
        X.append(crop)
        y.append(CLASS_TO_IDX[ch])

    # Add explicit SPACE samples for spaces in the label
    for ch in bottom_target_full:
        if ch == " ":
            X.append(make_space_crop())
            y.append(CLASS_TO_IDX[" "])

    good += 1

X = np.array(X, dtype=np.float32) / 255.0
X = X[..., None]
y = np.array(y, dtype=np.int64)

print("good images:", good)
print("bad images:", bad)
print("X shape:", X.shape)
print("y shape:", y.shape)
print("unique classes:", len(set(y.tolist())))
print("some bad examples:", bad_examples[:10])

counts = np.bincount(y, minlength=len(CLASSES))

print("total samples:", len(y))
print("min per class:", counts.min())
print("missing classes:", [DISPLAY_CLASSES[i] for i in range(len(CLASSES)) if counts[i] == 0])

plt.figure(figsize=(14, 4))
plt.bar(DISPLAY_CLASSES, counts)
plt.title("Character distribution (including space)")
plt.xlabel("Class")
plt.ylabel("Count")
plt.xticks(rotation=90)
plt.grid(axis="y", linestyle="--", alpha=0.5)
plt.show()

plt.figure(figsize=(12, 8))
for i in range(16):
    idx = random.randint(0, len(X) - 1)
    plt.subplot(4, 4, i + 1)
    plt.imshow(X[idx].squeeze(), cmap="gray")
    plt.title(DISPLAY_CLASSES[y[idx]])
    plt.axis("off")
plt.tight_layout()
plt.show()

num_classes = len(CLASSES)
Y = tf.keras.utils.to_categorical(y, num_classes)

X_train, X_val, Y_train, Y_val, y_train_idx, y_val_idx = train_test_split(
    X, Y, y,
    test_size=0.2,
    random_state=0,
    stratify=y
)

print("Train:", X_train.shape, Y_train.shape)
print("Val:  ", X_val.shape, Y_val.shape)

class_weights_arr = compute_class_weight(
    class_weight="balanced",
    classes=np.unique(y_train_idx),
    y=y_train_idx
)
class_weights = {int(c): float(w) for c, w in zip(np.unique(y_train_idx), class_weights_arr)}

print("class weights:")
for k in sorted(class_weights.keys()):
    print(DISPLAY_CLASSES[k], "->", round(class_weights[k], 3))

data_augmentation = tf.keras.Sequential([
    tf.keras.layers.RandomRotation(0.03),
    tf.keras.layers.RandomTranslation(0.05, 0.05),
    tf.keras.layers.RandomZoom(0.08),
], name="data_augmentation")

model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(32, 32, 1)),

    data_augmentation,

    tf.keras.layers.Conv2D(32, 3, padding="same", use_bias=False),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.ReLU(),
    tf.keras.layers.MaxPool2D(),

    tf.keras.layers.Conv2D(64, 3, padding="same", use_bias=False),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.ReLU(),
    tf.keras.layers.MaxPool2D(),

    tf.keras.layers.Conv2D(128, 3, padding="same", use_bias=False),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.ReLU(),
    tf.keras.layers.MaxPool2D(),

    tf.keras.layers.Conv2D(128, 3, padding="same", use_bias=False),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.ReLU(),

    # Better than Flatten for small datasets
    tf.keras.layers.GlobalAveragePooling2D(),
    tf.keras.layers.Dense(256, activation="relu"),
    tf.keras.layers.Dropout(0.35),
    tf.keras.layers.Dense(num_classes, activation="softmax"),
])

model.compile(
    optimizer=tf.keras.optimizers.Adam(1e-4),
    loss=tf.keras.losses.CategoricalCrossentropy(label_smoothing=0.05),
    metrics=["accuracy"]
)

model.summary()

# 17
callbacks = [
    tf.keras.callbacks.EarlyStopping(
        monitor="val_accuracy",
        patience=5,
        restore_best_weights=True
    ),
    tf.keras.callbacks.ReduceLROnPlateau(
        monitor="val_loss",
        factor=0.5,
        patience=2,
        min_lr=1e-6,
        verbose=1
    )
]

hist = model.fit(
    X_train, Y_train,
    validation_data=(X_val, Y_val),
    epochs=30,
    batch_size=64,
    callbacks=callbacks,
    class_weight=class_weights,
    verbose=1
)

plt.figure()
plt.plot(hist.history["loss"], label="train loss")
plt.plot(hist.history["val_loss"], label="val loss")
plt.xlabel("epoch")
plt.ylabel("loss")
plt.legend()
plt.show()

plt.figure()
plt.plot(hist.history["accuracy"], label="train acc")
plt.plot(hist.history["val_accuracy"], label="val acc")
plt.xlabel("epoch")
plt.ylabel("accuracy")
plt.legend()
plt.show()

pred_probs = model.predict(X_val[:16], verbose=0)
pred_idx = np.argmax(pred_probs, axis=1)
true_idx = np.argmax(Y_val[:16], axis=1)

plt.figure(figsize=(12, 8))
for i in range(16):
    plt.subplot(4, 4, i + 1)
    plt.imshow(X_val[i].squeeze(), cmap="gray")
    plt.title(f"T:{DISPLAY_CLASSES[true_idx[i]]} P:{DISPLAY_CLASSES[pred_idx[i]]}")
    plt.axis("off")
plt.tight_layout()
plt.show()

val_loss, val_acc = model.evaluate(X_val, Y_val, verbose=0)
print("Validation accuracy:", val_acc)

# 20
pred_probs = model.predict(X_val, verbose=0)
pred_labels = np.argmax(pred_probs, axis=1)
true_labels = np.argmax(Y_val, axis=1)

accuracy = np.mean(pred_labels == true_labels)
print("Manual accuracy:", accuracy)

cm = confusion_matrix(true_labels, pred_labels)

plt.figure(figsize=(12, 10))
plt.imshow(cm, interpolation="nearest")
plt.colorbar()
plt.xticks(range(len(DISPLAY_CLASSES)), DISPLAY_CLASSES, rotation=90)
plt.yticks(range(len(DISPLAY_CLASSES)), DISPLAY_CLASSES)
plt.xlabel("Predicted")
plt.ylabel("True")
plt.title("Confusion Matrix")
plt.tight_layout()
plt.show()

BASE_MODEL_KERAS_PATH = "/content/drive/MyDrive/sign_char_model.keras"
BASE_MODEL_TFLITE_PATH = "/content/drive/MyDrive/sign_char_model.tflite"
CLASSES_PATH = "/content/drive/MyDrive/sign_char_classes.json"

model.save(BASE_MODEL_KERAS_PATH)
print("saved keras model:", BASE_MODEL_KERAS_PATH)

converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

with open(BASE_MODEL_TFLITE_PATH, "wb") as f:
    f.write(tflite_model)

print("Saved TFLite model to:", BASE_MODEL_TFLITE_PATH)

with open(CLASSES_PATH, "w") as f:
    json.dump(CLASSES, f)

print("Saved class list to:", CLASSES_PATH)

interpreter = tf.lite.Interpreter(model_path=BASE_MODEL_TFLITE_PATH)
interpreter.allocate_tensors()

input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

print("Input details:", input_details)
print("Output details:", output_details)

x_test = X_val[0:1].astype(np.float32)

interpreter.set_tensor(input_details[0]['index'], x_test)
interpreter.invoke()
output = interpreter.get_tensor(output_details[0]['index'])

pred_idx = int(np.argmax(output))
true_idx = int(np.argmax(Y_val[0]))

print("True:", DISPLAY_CLASSES[true_idx])
print("Pred:", DISPLAY_CLASSES[pred_idx])
print("Confidence:", float(np.max(output)))

real_files = sorted([
    f for f in os.listdir(REAL_LINE_DIR)
    if f.lower().endswith((".png", ".jpg", ".jpeg"))
])

print("num real line files:", len(real_files))
print(real_files[:10])

# 24
def parse_line_filename(fname):
    """
    Real line-image filenames:
    - ABC~12_001.png  -> "ABC 12"
    - AB 12_001.png   -> "AB 12"
    """
    stem = os.path.splitext(fname)[0]
    text = stem.split("_")[0]
    return normalize_space_text(text)

def segment_real_line_image(line_bgr, debug=False):
    """
    Segment visible characters only from a real line image.
    Spaces are not segmented here; they are added later as synthetic blank crops.
    """
    hsv = cv2.cvtColor(line_bgr, cv2.COLOR_BGR2HSV)

    lower_blue = np.array([90, 40, 40])
    upper_blue = np.array([150, 255, 255])
    mask = cv2.inRange(hsv, lower_blue, upper_blue)

    mask = cv2.medianBlur(mask, 3)
    kernel = np.ones((2, 2), np.uint8)
    mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, kernel, iterations=1)

    H, W = mask.shape[:2]

    col_sum = np.sum(mask > 0, axis=0).astype(float)
    col_sum = col_sum / (np.max(col_sum) + 1e-6)

    threshold = 0.05
    splits = []
    in_char = False
    start = 0

    for i, val in enumerate(col_sum):
        if val > threshold and not in_char:
            start = i
            in_char = True
        elif val <= threshold and in_char:
            end = i
            splits.append((start, end))
            in_char = False

    if in_char:
        splits.append((start, W))

    boxes = []
    for (x0, x1) in splits:
        width = x1 - x0

        if width < 3:
            continue
        if width > 0.35 * W:
            continue

        col_region = mask[:, x0:x1]
        rows = np.where(np.sum(col_region > 0, axis=1) > 0)[0]

        if len(rows) == 0:
            continue

        y0 = rows[0]
        y1 = rows[-1]

        w = width
        h = y1 - y0 + 1

        if h < 0.35 * H:
            continue

        boxes.append((x0, y0, w, h))

    if len(boxes) == 0:
        cnts, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        for c in cnts:
            x, y, w, h = cv2.boundingRect(c)

            if w * h < 20:
                continue
            if h < 0.35 * H:
                continue
            if w > 0.35 * W:
                continue

            boxes.append((x, y, w, h))

    boxes = sorted(boxes, key=lambda b: b[0])

    crops = []
    for x, y, w, h in boxes:
        pad = max(2, int(0.12 * max(w, h)))
        x0 = max(0, x - pad)
        y0 = max(0, y - pad)
        x1 = min(W, x + w + pad)
        y1 = min(H, y + h + pad)

        crop = line_bgr[y0:y1, x0:x1]
        processed = preprocess_training_crop(crop)
        crops.append(processed)

    if debug:
        dbg = cv2.cvtColor(mask, cv2.COLOR_GRAY2BGR)
        for x, y, w, h in boxes:
            cv2.rectangle(dbg, (x, y), (x + w, y + h), (0, 255, 0), 2)
        return crops, mask, dbg, boxes

    return crops, mask, None, boxes

# 26
sample_real = random.choice(real_files)
sample_real_path = os.path.join(REAL_LINE_DIR, sample_real)
sample_img = cv2.imread(sample_real_path)

sample_text = parse_line_filename(sample_real)
real_crops, real_mask, real_dbg, real_boxes = segment_real_line_image(sample_img, debug=True)

print("sample file:", sample_real)
print("expected text:", repr(sample_text))
print("visible-only expected:", sample_text.replace(" ", ""))
print("detected boxes:", len(real_boxes))

plt.figure(figsize=(12, 4))
plt.subplot(1, 3, 1)
plt.imshow(cv2.cvtColor(sample_img, cv2.COLOR_BGR2RGB))
plt.title("Original")
plt.axis("off")

plt.subplot(1, 3, 2)
plt.imshow(real_mask, cmap="gray")
plt.title("Mask")
plt.axis("off")

plt.subplot(1, 3, 3)
plt.imshow(cv2.cvtColor(real_dbg, cv2.COLOR_BGR2RGB))
plt.title("Boxes")
plt.axis("off")
plt.show()

plt.figure(figsize=(12, 3))
for i, crop in enumerate(real_crops[:10]):
    plt.subplot(1, min(10, len(real_crops)), i + 1)
    plt.imshow(crop, cmap="gray")
    plt.axis("off")
plt.tight_layout()
plt.show()

X_real = []
y_real = []

good_real = 0
bad_real = 0
bad_real_examples = []

for fname in real_files:
    path = os.path.join(REAL_LINE_DIR, fname)
    img = cv2.imread(path)

    if img is None:
        bad_real += 1
        bad_real_examples.append((fname, "imread failed"))
        continue

    text_full = parse_line_filename(fname)
    text_visible = text_full.replace(" ", "")

    crops, _, _, boxes = segment_real_line_image(img, debug=False)

    if len(crops) != len(text_visible):
        bad_real += 1
        bad_real_examples.append((fname, f"visible count mismatch: got {len(crops)} expected {len(text_visible)}"))
        continue

    for crop, ch in zip(crops, text_visible):
        if ch not in CLASS_TO_IDX:
            continue
        X_real.append(crop)
        y_real.append(CLASS_TO_IDX[ch])

    # Add explicit SPACE class samples
    for ch in text_full:
        if ch == " ":
            X_real.append(make_space_crop())
            y_real.append(CLASS_TO_IDX[" "])

    good_real += 1

X_real = np.array(X_real, dtype=np.float32) / 255.0
X_real = X_real[..., None]
y_real = np.array(y_real, dtype=np.int64)

print("good real line images:", good_real)
print("bad real line images:", bad_real)
print("X_real shape:", X_real.shape)
print("y_real shape:", y_real.shape)
print("some bad real examples:", bad_real_examples[:10])

print("first 30 bad examples:")
for ex in bad_real_examples[:30]:
    print(ex)

failed = bad_real_examples[:20]

for fname, reason in failed:
    path = os.path.join(REAL_LINE_DIR, fname)
    img = cv2.imread(path)
    if img is None:
        continue

    text = parse_line_filename(fname)
    crops, mask, dbg, boxes = segment_real_line_image(img, debug=True)

    print("FILE:", fname)
    print("TEXT:", repr(text))
    print("VISIBLE TEXT:", text.replace(" ", ""))
    print("REASON:", reason)
    print("BOX COUNT:", len(boxes))
    print("-" * 40)

    plt.figure(figsize=(12, 4))
    plt.subplot(1, 3, 1)
    plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
    plt.title(f"Original: {fname}")
    plt.axis("off")

    plt.subplot(1, 3, 2)
    plt.imshow(mask, cmap="gray")
    plt.title("Mask")
    plt.axis("off")

    plt.subplot(1, 3, 3)
    plt.imshow(cv2.cvtColor(dbg, cv2.COLOR_BGR2RGB))
    plt.title(f"Boxes ({len(boxes)})")
    plt.axis("off")

    plt.show()

"""Refine the model!"""

# 30
counts_real = np.bincount(y_real, minlength=len(CLASSES))

print("total real char samples:", len(y_real))
print("min per class:", counts_real.min())
print("missing classes:", [DISPLAY_CLASSES[i] for i in range(len(CLASSES)) if counts_real[i] == 0])

plt.figure(figsize=(14, 4))
plt.bar(DISPLAY_CLASSES, counts_real)
plt.title("Real fine-tuning character distribution (including space)")
plt.xlabel("Class")
plt.ylabel("Count")
plt.xticks(rotation=90)
plt.grid(axis="y", linestyle="--", alpha=0.5)
plt.show()

plt.figure(figsize=(12, 8))
for i in range(16):
    idx = random.randint(0, len(X_real) - 1)
    plt.subplot(4, 4, i + 1)
    plt.imshow(X_real[idx].squeeze(), cmap="gray")
    plt.title(DISPLAY_CLASSES[y_real[idx]])
    plt.axis("off")
plt.tight_layout()
plt.show()

# Build class weights for fine-tuning too
real_class_weights_arr = compute_class_weight(
    class_weight="balanced",
    classes=np.unique(y_real),
    y=y_real
)
real_class_weights = {int(c): float(w) for c, w in zip(np.unique(y_real), real_class_weights_arr)}

print("real fine-tune class weights:")
for k in sorted(real_class_weights.keys()):
    print(DISPLAY_CLASSES[k], "->", round(real_class_weights[k], 3))

#32 Fine tuning!
Y_real = tf.keras.utils.to_categorical(y_real, len(CLASSES))

# Fine-tune gently
model.compile(
    optimizer=tf.keras.optimizers.Adam(5e-5),
    loss=tf.keras.losses.CategoricalCrossentropy(label_smoothing=0.03),
    metrics=["accuracy"]
)

callbacks = [
    tf.keras.callbacks.EarlyStopping(
        monitor="val_accuracy",
        patience=4,
        restore_best_weights=True
    ),
    tf.keras.callbacks.ReduceLROnPlateau(
        monitor="val_loss",
        factor=0.5,
        patience=2,
        min_lr=1e-6,
        verbose=1
    )
]

hist_real = model.fit(
    X_real, Y_real,
    validation_split=0.15,
    epochs=15,
    batch_size=32,
    callbacks=callbacks,
    class_weight=real_class_weights,
    verbose=1
)

plt.figure()
plt.plot(hist_real.history["loss"], label="train loss")
plt.plot(hist_real.history["val_loss"], label="val loss")
plt.xlabel("epoch")
plt.ylabel("loss")
plt.legend()
plt.show()

plt.figure()
plt.plot(hist_real.history["accuracy"], label="train acc")
plt.plot(hist_real.history["val_accuracy"], label="val acc")
plt.xlabel("epoch")
plt.ylabel("accuracy")
plt.legend()
plt.show()

FINETUNED_MODEL_KERAS_PATH = "/content/drive/MyDrive/sign_char_model_finetuned.keras"
FINETUNED_MODEL_TFLITE_PATH = "/content/drive/MyDrive/sign_char_model_finetuned.tflite"
CLASSES_PATH = "/content/drive/MyDrive/sign_char_classes.json"

model.save(FINETUNED_MODEL_KERAS_PATH)
print("saved keras model:", FINETUNED_MODEL_KERAS_PATH)

converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

with open(FINETUNED_MODEL_TFLITE_PATH, "wb") as f:
    f.write(tflite_model)

print("Saved TFLite model to:", FINETUNED_MODEL_TFLITE_PATH)

with open(CLASSES_PATH, "w") as f:
    json.dump(CLASSES, f)

print("Saved class list to:", CLASSES_PATH)

interpreter = tf.lite.Interpreter(model_path=FINETUNED_MODEL_TFLITE_PATH)
interpreter.allocate_tensors()

input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

x_test = X_real[0:1].astype(np.float32)

interpreter.set_tensor(input_details[0]['index'], x_test)
interpreter.invoke()
output = interpreter.get_tensor(output_details[0]['index'])

pred_idx = int(np.argmax(output))
true_idx = int(y_real[0])

print("True:", DISPLAY_CLASSES[true_idx])
print("Pred:", DISPLAY_CLASSES[pred_idx])
print("Confidence:", float(np.max(output)))